name: Cross platform build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          if [ $RUNNER_OS == "macOS" ]; then
            brew install cmake gcc
          else
            sudo apt update && sudo apt install -y cmake g++
          fi

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc

      - name: Create build directory (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          if [ ! -d "build" ]; then
            mkdir build
          else
            echo "Build directory already exists."
          fi

      - name: Create build directory (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          if [ ! -d "build" ]; then
            mkdir build
          else
            echo "Build directory already exists."
          fi

      - name: Configure CMake project (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          cd build
          cmake ..
        
      - name: Configure CMake project (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          cd build
          cmake ..

      - name: Build C++ code (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          cd build
          cmake --build .
        
      - name: Build C++ code (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          cd build
          cmake --build .

      - name: Run tests (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          cd build
          ./main

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          cd build
          ./main.exe
